### ISSUE TITLE
unhandled exception in parsing invalid css, on'error' method not getting invoked 

### ISSUE THREAD

**Issue by hiteshdua1** [dustinspecker/gulp-modify-css-urls#50]
Hi @dustinspecker ,

I have encountered the following error while running your gulp plugin.

```
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: undefined:10:8: property missing ':'
    at error (D:\sim5code-server\DeploymentScripts\Gulp\Packaging\node_modules\css\lib\parse\index.js:62:15)
    at declaration (D:\sim5code-server\DeploymentScripts\Gulp\Packaging\node_modules\css\lib\parse\index.js:223:33)
    at declarations (D:\sim5code-server\DeploymentScripts\Gulp\Packaging\node_modules\css\lib\parse\index.js:252:19)
    at rule (D:\sim5code-server\DeploymentScripts\Gulp\Packaging\node_modules\css\lib\parse\index.js:560:21)
    at rules (D:\sim5code-server\DeploymentScripts\Gulp\Packaging\node_modules\css\lib\parse\index.js:117:70)
    at stylesheet (D:\sim5code-server\DeploymentScripts\Gulp\Packaging\node_modules\css\lib\parse\index.js:81:21)
    at module.exports (D:\sim5code-server\DeploymentScripts\Gulp\Packaging\node_modules\css\lib\parse\index.js:564:20)
    at rework (D:\sim5code-server\DeploymentScripts\Gulp\Packaging\node_modules\rework\index.js:27:21)
    at modifyUrls (D:\sim5code-server\DeploymentScripts\Gulp\Packaging\node_modules\gulp-modify-css-urls\lib\index.js:32:31)
    at DestroyableTransform._transform (D:\sim5code-server\DeploymentScripts\Gulp\Packaging\node_modules\gulp-modify-css-urls\lib\index.js:62:28)
    at DestroyableTransform.Transform._read (D:\sim5code-server\DeploymentScripts\Gulp\Packaging\node_modules\gulp-modify-css-urls\node_modules\through2\node_modules\readable-stream\lib\_stream_transform.js:159:10)
    at DestroyableTransform.Transform._write (D:\sim5code-server\DeploymentScripts\Gulp\Packaging\node_modules\gulp-modify-css-urls\node_modules\through2\node_modules\readable-stream\lib\_stream_transform.js:147:83)
    at doWrite (D:\sim5code-server\DeploymentScripts\Gulp\Packaging\node_modules\gulp-modify-css-urls\node_modules\through2\node_modules\readable-stream\lib\_stream_writable.js:313:64)
```

This error is due to incorrect CSS parsing.I corrected this and the gulp plugin worked fine.

But whenever there is an incorrect css, the plugin throws an unhandeled excpetion and fails.

I even tried adding the ```on('error')``` method , but that does not get invoked.

Please look into the issue.
I believe, you have missed try catch handling and the error is not being handled in your index.js file.

I am proposing the following fix. If you feel this is correct, please let me know, and i will create the pull request for the same.

Fix in index.js
```
/**
* Pushes along files with transformed URLs
* @param {Object} [options={}] - same as described for modifyUrls function
* @return {Stream} - file with transformed URLs
*/
module.exports = function () {
  var options = arguments.length <= 0 || arguments[0] === undefined ? {} : arguments[0];
 
  return _through2.default.obj(function (file, enc, cb) {
    try {
      var modifiedContents = modifyUrls(file.path, file.contents.toString(), options);
    }
    catch(err) {
      console.error(err);
      return cb(new Error(`modifyUrls - ${file.path}`));
    }
 
    file.contents = new Buffer(modifiedContents);
 
    this.push(file);
 
    cb();
  });
};
```

Regards,
Hitesh Dua

**Comment by dustinspecker** [comment]
Hey @hiteshdua1,

This all looks good to me. Would you be to call the callback with the actual error, though? Other than that, this all looks great! Thank you for looking into this!

**Comment by dustinspecker** [comment]
Hey @hiteshdua1 

Can you try the latest release?

I apologize for the delay in getting this fixed.
